### ISSUE TITLE
`tools/generate_samples_gpt.py` error with given context

### ISSUE THREAD

**Issue by haven-jeon** [SKT-LSL/Megatron-LM#12]
generate_sample_gpt.py 실행시 주어인 입력 context가 있을 경우 아래와 같은 에러가 발생함

```
CHECKPOINT_PATH=checkpoints/gpt2_1B_test_metalearn
TOK_MODEL=tools/kogpt2.2.2_tokenizer-51200-balanced_x10.json

GPUS_PER_NODE=4
MASTER_ADDR=localhost
MASTER_PORT=6015
NNODES=1
NODE_RANK=0
WORLD_SIZE=$(($GPUS_PER_NODE*$NNODES))
DISTRIBUTED_ARGS="--nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port $MASTER_PORT"



docker run --shm-size=4g --rm --privileged --env CUDA_VISIBLE_DEVICES=$SLURM_JOB_GPUS  -v /t2meta/:/t2meta/ acrconvai.azurecr.io/mlm:0.1  bash -c "cd /t2meta/user/gogamza/work/os_work/Megatron-LM/; PYTHONPATH=. python -m torch.distributed.launch $DISTRIBUTED_ARGS tools/generate_samples_gpt.py \
                --num-layers 24 \
                --hidden-size 1920 \
                --load $CHECKPOINT_PATH \
                --num-attention-heads 16 \
                --max-position-embeddings 1024 \
                --tokenizer-type KoGPTTokenizer \
                --fp16 \
                --micro-batch-size 2 \
                --seq-length 1024 \
                --out-seq-length 1024 \
                --temperature 0.8 \
                --tokenizer-file $TOK_MODEL \
                --sample-input-file sample_input.txt \
                --sample-output-file sample_output.txt \
                --num-samples 0 \
                --top_p 1.0 \
                --recompute \
                --tensor-model-parallel-size 2 \
                --genfile test_gen.txt \
                --pipeline-model-parallel-size 2"
```

```
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 117, in <module>
    main()
  File "tools/generate_samples_gpt.py", line 108, in main
    generate_samples_input_from_file(model)
  File "/t2meta/user/gogamza/work/os_work/Megatron-LM/megatron/text_generation_utils.py", line 135, in generate_samples_input_from_file
    input_info = [terminate_runs, raw_text_len, context_length]
UnboundLocalError: local variable 'context_length' referenced before assignment
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 117, in <module>
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 117, in <module>
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 117, in <module>
    main()
  File "tools/generate_samples_gpt.py", line 108, in main
    main()
  File "tools/generate_samples_gpt.py", line 108, in main
    main()
  File "tools/generate_samples_gpt.py", line 108, in main
    generate_samples_input_from_file(model)
  File "/t2meta/user/gogamza/work/os_work/Megatron-LM/megatron/text_generation_utils.py", line 137, in generate_samples_input_from_file
    generate_samples_input_from_file(model)    
generate_samples_input_from_file(model)
  File "/t2meta/user/gogamza/work/os_work/Megatron-LM/megatron/text_generation_utils.py", line 137, in generate_samples_input_from_file
  File "/t2meta/user/gogamza/work/os_work/Megatron-LM/megatron/text_generation_utils.py", line 137, in generate_samples_input_from_file
    torch.distributed.all_reduce(input_info_tensor,
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
    torch.distributed.all_reduce(input_info_tensor,
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
    torch.distributed.all_reduce(input_info_tensor,
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: Connection reset by peer
    work = group.allreduce([tensor], opts)
RuntimeError: Connection reset by peer    
work = group.allreduce([tensor], opts)
RuntimeError: Connection reset by peer
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 303, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 294, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/generate_samples_gpt.py', '--local_rank=3', '--num-layers', '24', '--hidden-size', '1920', '--load', 'checkpoints/gpt2_1B_test_metalearn', '--num-attention-heads', '16', '--max-position-embeddings', '1024', '--tokenizer-type', 'KoGPTTokenizer', '--fp16', '--micro-batch-size', '2', '--seq-length', '1024', '--out-seq-length', '1024', '--temperature', '0.8', '--tokenizer-file', 'tools/kogpt2.2.2_tokenizer-51200-balanced_x10.json', '--sample-input-file', 'sample_input.txt', '--sample-output-file', 'sample_output.txt', '--num-samples', '0', '--top_p', '1.0', '--recompute', '--tensor-model-parallel-size', '2', '--genfile', 'test_gen.txt', '--pipeline-model-parallel-size', '2']' returned non-zero exit status 1.
```

**Comment by haven-jeon** [comment]
input 파일의 마지막 라인이 newline이여야 생성 가능함 ...
